# Generated by Django 5.1.4 on 2025-01-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
