# Generated by Django 5.1.4 on 2025-01-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_alter_comments_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='subject',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
