# Generated by Django 5.1.4 on 2025-01-01 11:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab7app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
