# Generated by Django 5.1.4 on 2025-01-05 06:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab7app', '0005_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 6, 39, 30, 893102, tzinfo=datetime.timezone.utc)),
        ),
    ]
