# Generated by Django 5.1.4 on 2025-01-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab7app', '0007_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
