# Generated by Django 5.1.4 on 2025-01-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maktab7app', '0010_post_created_at_alter_post_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='login_require',
            field=models.BooleanField(default=False),
        ),
    ]
